name: avatar_better_pro
description: "This is a complete avatar package that you can use for your profile and avatar."
version: 0.0.5
homepage: https://github.com/SwanFlutter/avatar_better_pro.git

platforms:
  android:
  ios:
  web:
  linux:
  windows:
  macos:

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  image_picker_platform_interface: ^2.10.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:


